"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Trevor Manz"
email = "trevor.j.manz@gmail.com"

[template-aliases]
'format_short_id(id)' = "id.shortest()"

[colors]
"diff token" = { underline = false }
"diff removed token" = { bg = "#221111" }
"diff added token" = { bg = "#002200" }

[aliases]
jj = []
l = ["log", "-r", "ancestors(reachable(@, mutable()), 2)"]

[ui]
default-command = "l"
diff-editor = ":builtin"
