"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Trevor Manz"
email = "trevor.j.manz@gmail.com"

[templates]
git_push_bookmark = '"manzt/" ++ description.first_line().lower().split_whitespace().join("-")'

[colors]
"diff token" = { underline = true }

[aliases]
jj = []
l = ["log", "-r", "ancestors(reachable(@, mutable()), 2)"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[ui]
default-command = "l"
diff-editor = ":builtin"
